## SRJ - NH3 - 1.8 A

In [1]:
import pennylane as qml
from pennylane import qchem
from pennylane import numpy as np
from itertools import chain
import time
import re
from scipy.optimize import minimize
ash_excitation = []
energies = []
excitations= []

X = qml.PauliX
Y = qml.PauliY
Z = qml.PauliZ
I = qml.Identity



#Molecular information
symbols = ["N","H","H","H"]
electrons = 10  # Number of electrons
orbitals = 20  # Number of spin orbitals
r_bohr = 1.8897259886  
coordinates = np.array([[0.0,0.0, 0.0], [0.0, 0.0, 1.80*r_bohr], [0.950353*r_bohr,0.0,-0.336000*r_bohr],[-0.475176*r_bohr, -0.823029*r_bohr, -0.336000*r_bohr]])
print("Coordinates are", coordinates)
active_electrons = 6  #3 from N and 3 from H
active_orbitals = 6  # Prince told me its spatial orbitals
core, active = qml.qchem.active_space(electrons, orbitals, active_electrons=active_electrons, active_orbitals=active_orbitals) # Spatial orbitals

H, qubits = qml.qchem.molecular_hamiltonian(symbols, coordinates, basis="sto-3g", method="pyscf", active_electrons=active_electrons, active_orbitals=active_orbitals)
print('Qubits are', qubits)
print("List of core orbitals: {:}".format(core))
print("List of active orbitals: {:}".format(active))
print("Number of qubits: {:}".format(2 * len(active)))
hf_state = qchem.hf_state(active_electrons, qubits)





def adaptvqesri(adapt_it, e_th):
    #Calculation of HF state
    dev = qml.device("lightning.qubit", wires=qubits)
    @qml.qnode(dev)
    def circuit(hf_state, active_electrons, qubits, H):
        print('Updated hf_state is', hf_state)  
        qml.BasisState(hf_state, wires=range(qubits))
        return qml.expval(H)   #Calculating the expectation value of the Hamiltonian
    
    # Commutator calculation for HF state
    @qml.qnode(dev)
    def commutator_0(H,w, k):  #H is the Hamiltonian, w is the operator, k is the basis state - HF state
        qml.BasisState(k, wires=range(qubits))
        res = qml.commutator(H, w)   #Calculating the commutator
        return qml.expval(res)
    
    # Commutator calculation for other states except HF state
    @qml.qnode(dev)
    def commutator_1(H,w, k): #H is the Hamiltonian, w is the operator, k is the basis state
        qml.StatePrep(k, wires=range(qubits))
        res = qml.commutator(H, w) #Calculating the commutator
        return qml.expval(res)

    #Energy calculation 
    @qml.qnode(dev)
    def ash(params, ash_excitation, hf_state, H):
        [qml.PauliX(i) for i in np.nonzero(hf_state)[0]]  #Appln of HF state
        for i, excitation in enumerate(ash_excitation):
            if len(ash_excitation[i]) == 4:
                qml.FermionicDoubleExcitation(weight=params[i], wires1=ash_excitation[i][2:][::-1], wires2=ash_excitation[i][:2][::-1])
            elif len(ash_excitation[i]) == 2:
                qml.FermionicSingleExcitation(weight=params[i], wires=list(range(ash_excitation[i][0], ash_excitation[i][1] + 1)))
        return qml.expval(H)  #Calculating the expectation value of the Hamiltonian
    
    # Calculation of New state, same as the above function but with the state return
    dev1 = qml.device("lightning.qubit", wires=qubits)
    @qml.qnode(dev1)
    def new_state(hf_state, ash_excitation, params):
        [qml.PauliX(i) for i in np.nonzero(hf_state)[0]] #Applying the HF state
        for i, excitations in enumerate(ash_excitation):
            if len(ash_excitation[i]) == 4:
                print('Exc. dealing right now is', ash_excitation[i])
                print('The params that are going in', params[i])
                qml.FermionicDoubleExcitation(weight=params[i], wires1=ash_excitation[i][2:][::-1], wires2=ash_excitation[i][:2][::-1])
            elif len(ash_excitation[i]) == 2:
                print('Single Exc. dealing right now is', ash_excitation[i])
                print('Single exc params that are going in', params[i])
                qml.FermionicSingleExcitation(weight=params[i], wires=list(range(ash_excitation[i][0], ash_excitation[i][1] + 1)))
        return qml.state()
    
    def cost(params):
        energy = ash(params, ash_excitation, hf_state, H)
        return energy

    def callback(params):
        print(f"Current parameters: {params}")
        print(f"Current cost: {cost(params)}\n")
    

    print('HF state is', circuit(hf_state, active_electrons, qubits, H))
    singles, doubles = qml.qchem.excitations(active_electrons, 2*active_orbitals)
    op1 =  [qml.fermi.FermiWord({(0, x[0]): "+", (1, x[1]): "-"}) for x in singles]
    op2 =  [qml.fermi.FermiWord({(0, x[0]): "+", (1, x[1]): "+", (2, x[2]): "-", (3, x[3]): "-"})for x in doubles]
    operator_pool = (op1) + (op2)  #Operator pool - Singles and Doubles
    print('Total excitations are', len(operator_pool))
    states = [hf_state]
    params = np.zeros(len(ash_excitation), requires_grad=True) 
    

    for j in range(adapt_it):
        print('The adapt iteration now is', j)  #Adapt iteration
        max_value = float('-inf')
        max_operator = None
        # Start with the most recent state (last state in the list)
        k = states[-1] if states else hf_state  # if states is empty, fall back to hf_state
       
        for i in operator_pool:
            print('The current excitation operator is', i)   #Current excitation operator - fermionic one
            w = qml.fermi.jordan_wigner(i)  #JW transformation
            if np.array_equal(k, hf_state): # If the current state is the HF state
                print('Print, if this is activated - HF state')
                current_value = abs(2*(commutator_0(H, w, k)))      #Commutator calculation is activated  
            else:
                current_value = abs(2*(commutator_1(H, w, k)))      #For other states, commutator calculation is activated
            print(f'The expectation value of {i} is', current_value)

            if current_value > max_value:
                max_value = current_value
                max_operator = i

        print(f"The highest operator value is {max_value} for operator {max_operator}")  #Highest operator value

        # Convert operator to excitations and append to ash_excitation
        indices_str = re.findall(r'\d+', str(max_operator))
        excitations = [int(index) for index in indices_str]
        print('Highest gradient excitation is', excitations)
        ash_excitation.append(excitations) #Appending the excitations to the ash_excitation
        print('The current status of ash_excitation is', ash_excitation)
        print('Moving towards parameters')
         #Parameters initialization
        params = np.append(params, 0.0)  #Parameters initialization
        print('The length of parameters is', params)


        #Energy calculation
        result = minimize(cost, params, method='powell', callback=callback, tol = e_th, options = {'disp': True, 'maxiter': 1e8})

        print("Final updated parameters:", result.x)
        print("Final cost:", result.fun)

        params= (result.x)
        energies.append(result.fun)
        print('Updated params are', params)
        print('Updated excitation are', ash_excitation)

        # New state generation - With the updated parameters
        ostate = new_state(hf_state, ash_excitation, params)
        print(qml.draw(new_state, max_length=100)(hf_state,ash_excitation,params))
        # Append the new state to the states list
        states.append(ostate)

    return energies, params, ash_excitation




Coordinates are [[ 0.          0.          0.        ]
 [ 0.          0.          3.40150678]
 [ 1.79590676  0.         -0.63494793]
 [-0.89795244 -1.55529929 -0.63494793]]
Qubits are 12
List of core orbitals: [0, 1]
List of active orbitals: [2, 3, 4, 5, 6, 7]
Number of qubits: 12


In [3]:
adaptvqesri(adapt_it=60, e_th=1e-12)
#started at 1.05 pm on 1st Apr

Updated hf_state is [1 1 1 1 1 1 0 0 0 0 0 0]
HF state is -55.23695115692377
Total excitations are 117
The adapt iteration now is 0
The current excitation operator is a⁺(0) a(6)
Print, if this is activated - HF state
The expectation value of a⁺(0) a(6) is 4.2832017872244597e-08
The current excitation operator is a⁺(0) a(8)
Print, if this is activated - HF state


/Users/s.poyyapakkam/miniconda3/envs/sri/lib/python3.12/site-packages/pennylane_lightning/core/_serialize.py:353: ComplexWarning: Casting complex values to real discards the imaginary part
  coeffs = np.array(coeffs).astype(self.rtype)


The expectation value of a⁺(0) a(8) is 9.578615737699538e-12
The current excitation operator is a⁺(0) a(10)
Print, if this is activated - HF state
The expectation value of a⁺(0) a(10) is 1.3730344032569786e-07
The current excitation operator is a⁺(1) a(7)
Print, if this is activated - HF state
The expectation value of a⁺(1) a(7) is 4.2832017872244597e-08
The current excitation operator is a⁺(1) a(9)
Print, if this is activated - HF state
The expectation value of a⁺(1) a(9) is 9.578615737699538e-12
The current excitation operator is a⁺(1) a(11)
Print, if this is activated - HF state
The expectation value of a⁺(1) a(11) is 1.373034402701867e-07
The current excitation operator is a⁺(2) a(6)
Print, if this is activated - HF state
The expectation value of a⁺(2) a(6) is 6.625978049568104e-08
The current excitation operator is a⁺(2) a(8)
Print, if this is activated - HF state
The expectation value of a⁺(2) a(8) is 1.0511185143807777e-06
The current excitation operator is a⁺(2) a(10)
Print, if

([-55.287783023132995,
  -55.29748007457647,
  -55.3161289138678,
  -55.32885272377553,
  -55.33714663586173,
  -55.339865842041284,
  -55.34188330224085,
  -55.34363622095137,
  -55.34526132415917,
  -55.34613622710589,
  -55.34694041011023,
  -55.34789708392103,
  -55.348322761244006,
  -55.348810389188785,
  -55.349070579922284,
  -55.34939643068553,
  -55.34961958115988,
  -55.35049861980366,
  -55.35082565478497,
  -55.351060579550975,
  -55.35129928986839,
  -55.35148968063281,
  -55.35286499083252,
  -55.35317835368597,
  -55.353450549162766,
  -55.353785686707575,
  -55.35404975554072,
  -55.3541078390775,
  -55.3547381119126,
  -55.35480854974989,
  -55.35492712940302,
  -55.35499239735334,
  -55.35505489819073,
  -55.355117497338966,
  -55.35520099608526,
  -55.355273345371515,
  -55.355296231020375,
  -55.35533772232684,
  -55.35538368881002,
  -55.35542516136745,
  -55.355452130211376,
  -55.3555316882848,
  -55.355578359352016,
  -55.355625876018664,
  -55.355663591903316,

## Time taken = 1026 mins = 17 hours

In [2]:
from pyscf import gto, scf, mcscf

# Define the molecule
mol = gto.M(
    atom='N 0.0 0.0 0.0; H 0.0 0.0 1.80; H 0.950353 0.0 -0.336000; H -0.475176 -0.823029 -0.336000;',
    basis='sto-3g',
    verbose=4  # Optional: Adjusts verbosity for output
)

# Perform Restricted Hartree-Fock calculation
mf = scf.RHF(mol)
mf.kernel()

# Get the HF energy
hf_energy = mf.e_tot
print("Hartree-Fock Ground State Energy:", hf_energy)

# Define the active space
ncas = 6  # Number of active orbitals - spatial it seems
nelecas = 6  # Number of electrons in the active space

# Set up the CASCI/CASSCF solver
mycas = mcscf.CASCI(mf, ncas, nelecas)

# Alternatively, use CASSCF for self-consistent optimization
# mycas = mcscf.CASSCF(mf, ncas, nelecas)

# Compute the CASCI/CASSCF energy
e_casci = mycas.kernel()

# Output the results
print("CASCI/CASSCF Ground State Energy:", e_casci)
print("Hartree-Fock Ground State Energy:", hf_energy)


System: uname_result(system='Darwin', node='chem177.chem.und.nodak.edu', release='23.6.0', version='Darwin Kernel Version 23.6.0: Fri Jul  5 17:53:24 PDT 2024; root:xnu-10063.141.1~2/RELEASE_ARM64_T6020', machine='arm64')  Threads 1
Python 3.12.8 | packaged by conda-forge | (main, Dec  5 2024, 14:19:53) [Clang 18.1.8 ]
numpy 1.26.4  scipy 1.15.1  h5py 3.12.1
Date: Tue Apr  1 13:02:21 2025
PySCF version 2.8.0
PySCF path  /Users/s.poyyapakkam/miniconda3/envs/sri/lib/python3.12/site-packages/pyscf

[CONFIG] conf_file None
[INPUT] verbose = 4
[INPUT] num. atoms = 4
[INPUT] num. electrons = 10
[INPUT] charge = 0
[INPUT] spin (= nelec alpha-beta = 2S) = 0
[INPUT] symmetry False subgroup None
[INPUT] Mole.unit = angstrom
[INPUT] Symbol           X                Y                Z      unit          X                Y                Z       unit  Magmom
[INPUT]  1 N      0.000000000000   0.000000000000   0.000000000000 AA    0.000000000000   0.000000000000   0.000000000000 Bohr   0.0
[INPUT] 

In [4]:
FCI = -55.3570150268498

-55.35588842648638 - FCI 

0.0011266003634204935

## 1.0A case  - done
## 1.2A case - talon
## 1.4A case - done 
## 1.6A case - Talon
## 1.8A case - Running 
## 2.0A - 4.2A case - Talon 